version: '3.2'

services:
  consul:
    image: consul:latest
    container_name: consul
    ports:
       - "8123:8500"
       - "8234:8600"
       - "8134:8300"
       - "8345:8301"
       - "8235:8302"
    volumes:
       - /data/consul:/consul/data:rw

  logstash:
    image: logstash:2.4
    container_name: logstash
    depends_on:
      - elasticsearch
    volumes:
      - /var/lib/docker/volumes/merce_platform_logs/_data/:/platform_logs:rw
      - logstash_info:/logstash:rw
    network_mode: "host"

  elasticsearch:
    image: elasticsearch:5.6
    container_name: es
    volumes:
      - es_config:/usr/share/elasticsearch/config:rw
      - es_logs:/usr/share/elasticsearch/logs:rw
    network_mode: "host"

  logserver:
    image: woven_logserver:latest
    container_name: logserver
    ports:
      - "8879:8879"
    depends_on:
      - consul
      - logstash
      - elasticsearch
    volumes:
      - logserver_conf:/woven_logserver/conf:rw
      - logserver_logs:/woven_logserver/log:rw
    network_mode: "host"

volumes:
   logstash_info:
   es_config:
   es_logs:
   logserver_conf:
   logserver_logs:
