version: "3.2"

services:    
   woven_gateway:
        image: woven_gateway:latest
        container_name: gateway
        ports:
            - "8515:8515"
            - "8400:8400"
        depends_on:
            - woven_mysql
        environment:
            WOVEN_BOOT: woven_gateway
        volumes:                      
            - "gateway_con:/woven_gateway/conf:rw"
            - "gateway_log:/woven_gateway/logs:rw"
            - /mytmp:/tmpmytmp
        network_mode: "host"

volumes:
   gateway_con:
   gateway_log:

