version: '3.2'

services:

    zookeeper1:
        image: ${ZOOKEEPER_IMAGE}
        container_name: zk11
        ports:
            - "2181:2181"
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zk12:2888:3888 server.3=zk13:2888:3888

    zookeeper2:
        image: ${ZOOKEEPER_IMAGE}
        container_name: zk12
        ports:
            - "2182:2181"
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zk11:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zk13:2888:3888

    zookeeper3:
        image: ${ZOOKEEPER_IMAGE}
        container_name: zk13
        ports:
            - "2183:2181"
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.11=zk11:2888:3888 server.2=zk12:2888:3888 server.3=0.0.0.0:2888:3888


    woven_mysql:
        image: ${MYSQL_IMAGE}
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: merce
        ports:
            - "3306:3306"
        depends_on:
            - zookeeper1
            - zookeeper2
            - zookeeper3
        volumes:
            - "mysql_conf:/etc/mysql/mysql.conf.d:rw"
            - "mysql_logs:/var/mysql/logs:rw"
            - "mysql_data:/var/lib/mysql:rw"
            - /mytmp:/tmp/mytmp
        network_mode: "host"



volumes:
    mysql_conf:
    mysql_data:
    mysql_logs:
