version: '2'

services:
  namenode:
    image: uhopper/hadoop-namenode:2.8.1

    # 配置好 docker 内的假域名
    hostname: baymax-deploy-03
    container_name: namenode
    network_mode: "host"
    volumes:
      # 自行修改数据卷的映射位置
      - /data/namenode:/hadoop/dfs/name
      - /mytmp:/tmp/mytmp
      - /mytmp/yarn-site.xml:/etc/hadoop/yarn-site.xml:rw
      - /mytmp/core-site.xml:/etc/hadoop/core-site.xml:rw
      - /mytmp/hdfs-site.xml:/etc/hadoop/hdfs-site.xml:rw
    environment:
      - CLUSTER_NAME=datanode1
      - CLUSTER_NAME=datanode2
      - CLUSTER_NAME=datanode3
      # 配置 hdfs 用户权限问题,不需要只允许 hadoop 用户访问
      - HDFS_CONF_dfs_permissions=false

  datanode1:
    image: uhopper/hadoop-datanode:2.8.1
    hostname: baymax-deploy-03
    container_name: datanode1
    network_mode: "host"
    volumes:
      - /datanode1:/hadoop/dfs/data
      - /mytmp:/tmp/mytmp
      - /mytmp/yarn-site.xml:/etc/hadoop/yarn-site.xml:rw
      #- /mytmp/core-site.xml:/etc/hadoop/core-site.xml:rw
      #- /mytmp/hdfs-site.xml:/etc/hadoop/hdfs-site.xml:rw

    environment:
      # 等价于在 core-site.xml 中配置 fs.defaultFS
      - CORE_CONF_fs_defaultFS=hdfs://baymax-deploy-03:8020
      # 等价于在 hdfs-site.xml 中配置 dfs.datanode.address
      - HDFS_CONF_dfs_datanode_address=0.0.0.0:50010
      # dfs.datanode.ipc.address 不使用默认端口的意义是在同一机器起多个 datanode，暴露端口需要不同
      - HDFS_CONF_dfs_datanode_ipc_address=0.0.0.0:50020
      # dfs.datanode.http.address
      - HDFS_CONF_dfs_datanode_http_address=0.0.0.0:50075

  datanode2:
    image: uhopper/hadoop-datanode:2.8.1
    hostname: baymax-deploy-03
    container_name: datanode2
    network_mode: "host"
    volumes:
      - /datanode2:/hadoop/dfs/data
      - /mytmp:/tmp/mytmp
      - /mytmp/yarn-site.xml:/etc/hadoop/yarn-site.xml:rw
      #- /mytmp/core-site.xml:/etc/hadoop/core-site.xml:rw
      #- /mytmp/hdfs-site.xml:/etc/hadoop/hdfs-site.xml:rw

    environment:
      - CORE_CONF_fs_defaultFS=hdfs://baymax-deploy-03:8020
      - HDFS_CONF_dfs_datanode_address=0.0.0.0:50012
      - HDFS_CONF_dfs_datanode_ipc_address=0.0.0.0:50022
      - HDFS_CONF_dfs_datanode_http_address=0.0.0.0:50072

  datanode3:
    image: uhopper/hadoop-datanode:2.8.1
    hostname: baymax-deploy-03
    container_name: datanode3
    network_mode: "host"
    volumes:
      - /datanode3:/hadoop/dfs/data
      - /mytmp:/tmp/mytmp
      - /mytmp/yarn-site.xml:/etc/hadoop/yarn-site.xml:rw
      #- /mytmp/core-site.xml:/etc/hadoop/core-site.xml:rw
      #- /mytmp/hdfs-site.xml:/etc/hadoop/hdfs-site.xml:rw

    environment:
      - CORE_CONF_fs_defaultFS=hdfs://baymax-deploy-03:8020
      - HDFS_CONF_dfs_datanode_address=0.0.0.0:50013
      - HDFS_CONF_dfs_datanode_ipc_address=0.0.0.0:50023
      - HDFS_CONF_dfs_datanode_http_address=0.0.0.0:50073

  resourcemanager:
    image: uhopper/hadoop-resourcemanager:2.8.1
    hostname: baymax-deploy-03
    container_name: resourcemanager
    network_mode: "host"
    volumes:
      - /mytmp:/tmp/mytmp
      - /mytmp/yarn-site.xml:/etc/hadoop/yarn-site.xml:rw
      #- /mytmp/core-site.xml:/etc/hadoop/core-site.xml:rw
      #- /mytmp/hdfs-site.xml:/etc/hadoop/hdfs-site.xml:rw

    environment:
      - CORE_CONF_fs_defaultFS=hdfs://baymax-deploy-03:8020
      - YARN_CONF_yarn_log___aggregation___enable=true

  nodemanager:
    image: uhopper/hadoop-nodemanager:2.8.1
    hostname: baymax-deploy-03
    container_name: nodemanager
    network_mode: "host"
    volumes:
      - /mytmp:/tmp/mytmp
      - /mytmp/yarn-site.xml:/etc/hadoop/yarn-site.xml:rw
      #- /mytmp/core-site.xml:/etc/hadoop/core-site.xml:rw
      #- /mytmp/hdfs-site.xml:/etc/hadoop/hdfs-site.xml:rw

    environment:
      - CORE_CONF_fs_defaultFS=hdfs://baymax-deploy-03:8020
      - YARN_CONF_yarn_resourcemanager_hostname=baymax-deploy-03
      - YARN_CONF_yarn_log___aggregation___enable=true
      - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs

  spark:
    image: uhopper/hadoop-spark:2.4.4_2.8.1
    hostname: baymax-deploy-03
    container_name: spark
    network_mode: "host"
    volumes:
      - /mytmp:/tmp/mytmp
      - /mytmp/yarn-site.xml:/etc/hadoop/yarn-site.xml:rw
      - /mytmp/slaves:/opt/spark-2.4.4/conf/slaves:rw
      - /mytmp/spark-defaults.conf:/opt/spark-2.4.4/conf/spark-defaults.conf:rw
      - /mytmp/spark-env.sh:/opt/spark-2.4.4/conf/spark-env.sh:rw
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://baymax-deploy-03:8020
      - YARN_CONF_yarn_resourcemanager_hostname=baymax-deploy-03
    command: tail -f /var/log/dmesg
