version: '3.2'

services:  
 
    zookeeper1:
        image: ${ZOOKEEPER_IMAGE}
        container_name: zk11
        ports:
            - "2181:2181"
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zk12:2888:3888 server.3=zk13:2888:3888
    
    zookeeper2:
        image: ${ZOOKEEPER_IMAGE}
        container_name: zk12
        ports:
            - "2182:2181"
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zk11:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zk13:2888:3888

    zookeeper3:
        image: ${ZOOKEEPER_IMAGE}
        container_name: zk13
        ports:
            - "2183:2181"
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.11=zk11:2888:3888 server.2=zk12:2888:3888 server.3=0.0.0.0:2888:3888
    

    woven_mysql: 
        image: ${MYSQL_IMAGE}
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: merce
        ports:
            - "3306:3306"
        depends_on:
            - zookeeper1
            - zookeeper2
            - zookeeper3
        volumes:
            - "mysql_conf:/etc/mysql/mysql.conf.d:rw"
            - "mysql_logs:/var/mysql/logs:rw"
            - "mysql_data:/var/lib/mysql:rw"
            - /mytmp:/tmp/mytmp
        network_mode: "host"

    woven_server:
        image: 192.168.2.81:5000/woven_platform:${PLATFORM_IMAGE_TAG}
        container_name: woven_server
        ports:
            - "17510:17510"
        environment:
            WOVEN_BOOT: woven_server
        depends_on:
            - woven_mysql
            - woven_discovery
        volumes:
            - "platform_logs:/woven_platform/logs:rw"
            - "platform_conf:/woven_platform/conf:rw"
            - "/etc/hadoop/conf:/etc/hadoop/conf"
            - "/app:/app"
            - /mytmp:/tmp/mytmp
        extra_hosts:
            - "baymax-deploy-03:192.168.2.81"
        network_mode: "host"

    woven_discovery:
        image: 192.168.2.81:5000/woven_platform:${PLATFORM_IMAGE_TAG}
        container_name: discovery
        depends_on:
            - woven_mysql
        ports:
            - "8518:8518"
        environment:
            WOVEN_BOOT: woven_discovery
        volumes:
            - "platform_logs:/woven_platform/logs:rw"
            - "platform_conf:/woven_platform/conf:rw"
            - "/etc/hadoop/conf:/etc/hadoop/conf"
            - "/app:/app"
            - /mytmp:/tmp/mytmp
        extra_hosts:
            - "baymax-deploy-03:192.168.2.81"
        network_mode: "host"
        
    woven_pipeline:
        image: 192.168.2.81:5000/woven_platform:${PLATFORM_IMAGE_TAG}
        container_name: woven_pipeline
        restart: always
        ports:
            - "17511:17511"
        environment:
            WOVEN_BOOT: woven_pipeline
        depends_on:
            - woven_mysql
            - woven_discovery
        volumes:
            - "platform_logs:/woven_platform/logs:rw"
            - "platform_conf:/woven_platform/conf:rw"
            - "/etc/hadoop/conf:/etc/hadoop/conf"
            - "/app:/app"
            - /mytmp:/tmp/mytmp
        extra_hosts:
            - "baymax-deploy-03:192.168.2.81"
        network_mode: "host"

    woven_more_executor:
        image: 192.168.2.81:5000/woven_platform:${PLATFORM_IMAGE_TAG}
        container_name: more_executor
        ports:
            - "17513:17513"
        depends_on:
            - woven_mysql
            - woven_discovery
        environment:
            WOVEN_BOOT: woven_executor_more
        volumes:
            - "platform_logs:/woven_platform/logs:rw"
            - "platform_conf:/woven_platform/conf:rw"
            - "/etc/hadoop/conf:/etc/hadoop/conf"
            - "/app:/app"
            - /mytmp:/tmp/mytmp
        extra_hosts:
            - "baymax-deploy-03:192.168.2.81"
        network_mode: "host"

    woven_df_executor:
        image: 192.168.2.81:5000/woven_platform:${PLATFORM_IMAGE_TAG}
        container_name: df-executor
        ports:
            - "17512:17512"
        depends_on:
            - woven_mysql
            - woven_discovery
        environment:
            WOVEN_BOOT: woven_executor_df
        volumes:
            - "platform_logs:/woven_platform/logs:rw"
            - "platform_conf:/woven_platform/conf:rw"
            - "/etc/hadoop/conf:/etc/hadoop/conf"
            - "/app:/app"
            - /mytmp:/tmp/mytmp
        network_mode: "host"
        extra_hosts:
            - "baymax-deploy-03:192.168.2.81"
    
    woven_livy:
        image: 192.168.2.81:5000/woven_platform:${PLATFORM_IMAGE_TAG}
        container_name: livy
        ports:
            - "8998:8998"
        depends_on:
            - woven_mysql
            - woven_discovery
        environment:
            WOVEN_BOOT: woven_livy
        volumes:
            - "livy_logs:/woven_platform/livy-server/logs:rw"
            - "livy_conf:/woven_platform/livy-server/conf:rw"
            - "/etc/hadoop/conf:/etc/hadoop/conf"
            - "/app:/app"
            - /mytmp:/tmp/mytmp
        network_mode: "host"
        extra_hosts:
            - "baymax-deploy-03:192.168.2.81"

    woven_app:
        image: 192.168.2.81:5000/woven_app:${WOVEN_APP_IMAGE_TAG}
        container_name: app
        ports:
            - "8514:8514"
        depends_on:
            - zookeeper1
            - zookeeper2
            - zookeeper3
            - woven_mysql
            - woven_discovery
        volumes:
            - "app_logs:/woven_app/logs:rw"
            - "app_conf:/woven_app/conf:rw"
            - "app_ui:/woven_app/woven-ui:rw"
            - "/etc/hadoop/conf:/etc/hadoop/conf"
            - "/app:/app"
            - /mytmp:/tmp/mytmp
        extra_hosts:
            - "baymax-deploy-03:192.168.2.81"
        network_mode: "host"
   
volumes:
    mysql_conf:
    mysql_data:
    mysql_logs:
    platform_conf:
    platform_logs:
    livy_logs:
    livy_conf: 
    app_logs:
    app_conf:
    app_ui:
