version ''

services:
      woven_app:
        image: 192.168.2.81:5000/woven_app:${WOVEN_APP_IMAGE_TAG}
        container_name: app
        ports:
            - "8514:8514"
        depends_on:
            - zookeeper1
            - zookeeper2
            - zookeeper3
            - woven_mysql
            - woven_discovery
        volumes:
            - "app_logs:/woven_app/logs:rw"
            - "app_conf:/woven_app/conf:rw"
            - "app_ui:/woven_app/woven-ui:rw"
            - "/etc/hadoop/conf:/etc/hadoop/conf"
            - "/app:/app"
            - /mytmp:/tmp/mytmp
        extra_hosts:
            - "baymax-deploy-03:192.168.2.81"
        network_mode: "host"



volumes:
    
    app_logs:
    app_conf:
    app_ui:

