
version: "3.2"

services:
    
   woven_gateway:
        image: 192.168.2.81:5000/woven_gateway:${GATEWAY_IMAGE_TAG}
        container_name: gateway
        ports:
            - "8515:8515"
            - "8400:8400"
        #depends_on:
            #- woven_mysql
        mac_address: 52:54:00:32:35:3b
        environment:
            WOVEN_BOOT: woven_gateway
        volumes:
           #- "woven_gateway_logs_11:/woven_gateway/logs:rw"
           #- "woven_gateway_conf_11:/woven_gateway/conf:rw"
            - "gateway_con:/woven_gateway/conf:rw"
            - "gateway_log:/woven_gateway/logs:rw"
            - /mytmp:/tmpmytmp
        extra_hosts:
            - "baymax-deploy-03:192.168.2.81"
        #network_mode: "host"
        networks:
             woven:
                  ipv4_address: "192.168.32.6"


volumes:
   gateway_con:
   gateway_log:
   #woven_gateway_logs_11:
   #woven_gateway_conf_11:

networks:
   woven:
      external: true


