#ACT_RU_JOB
ALTER TABLE ACT_RU_JOB DROP FOREIGN KEY ACT_FK_JOB_EXCEPTION;
ALTER TABLE ACT_RU_JOB DROP INDEX ACT_FK_JOB_EXCEPTION;

#ACT_RU_JOB
ALTER TABLE ACT_RU_EXECUTION DROP FOREIGN KEY ACT_FK_EXE_PROCDEF;
ALTER TABLE ACT_RU_EXECUTION DROP FOREIGN KEY ACT_FK_EXE_SUPER;
ALTER TABLE ACT_RU_EXECUTION DROP INDEX ACT_FK_EXE_PROCDEF;
ALTER TABLE ACT_RU_EXECUTION DROP INDEX ACT_FK_EXE_SUPER;